version: '3.8'
services:
  server:
    build: .
    ports:
      - "3005:3005"
    volumes:
      - .:/app
    command: npm run dev

  client:
    build: 
      context: ./client
    ports:
      - "3006:3005"
    volumes:
      - ./client:/app
    command: npm run dev
