name: Moneysaver

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Build the client first
      - name: Build client
        run: |
          cd client
          npm install
          npm run build
      
      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moneysaver-server .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moneysaver-client -f client/Dockerfile client
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/moneysaver-server
          docker push ${{ secrets.DOCKER_USERNAME }}/moneysaver-client