name: Moneysaver

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build client
        run: |
          cd client
          rm -rf node_modules package-lock.json
          npm ci --legacy-peer-deps
          npm run build
          ls -la dist  # Verify build output

      
      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moneysaver-server .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moneysaver-client -f client/Dockerfile client
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/moneysaver-server
          docker push ${{ secrets.DOCKER_USERNAME }}/moneysaver-client
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 95.179.191.48
          username: kendo
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/moneysaver-server
            docker pull ${{ secrets.DOCKER_USERNAME }}/moneysaver-client
            docker stop server client || true
            docker rm server client || true
            docker run -d --name server -p 3005:3005 ${{ secrets.DOCKER_USERNAME }}/moneysaver-server
            docker run -d --name client -p 3006:80 ${{ secrets.DOCKER_USERNAME }}/moneysaver-client
