name: Moneysaver

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-tailwind-app .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-tailwind-app
      
      - name: Setup SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H 95.179.191.48 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
        
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 95.179.191.48
          username: kendo
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/moneysaver:latest
            docker stop react-app || true
            docker rm react-app || true
            docker run -d --name react-app -p 3005:3005 ${{ secrets.DOCKER_USERNAME }}/react-tailwind-app
